version: '3.8'

services:
  jenkins:
    build: .
    container_name: jenkins-master
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config:/var/jenkins_config
      - ./secrets:/var/jenkins_secrets
      - ./logs:/var/jenkins_logs
    environment:
      # Jenkins Configuration
      - JENKINS_OPTS=--httpPort=8080
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
      
      # Azure DevOps Credentials
      - AZURE_DEVOPS_USERNAME=${AZURE_DEVOPS_USERNAME}
      - AZURE_DEVOPS_PAT=${AZURE_DEVOPS_PAT}
      - AZURE_DEVOPS_NPM_TOKEN=${AZURE_DEVOPS_NPM_TOKEN}
      
      # Jenkins Admin Password
      - JENKINS_ADMIN_PASSWORD=${JENKINS_ADMIN_PASSWORD}
    networks:
      - jenkins-network

volumes:
  jenkins_home:
    driver: local

networks:
  jenkins-network:
    driver: bridge 