jenkins:
  systemMessage: "Jenkins configurado con Configuration as Code"
  numExecutors: 2
  scmCheckoutRetryCount: 3
  mode: NORMAL
  
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "admin"
          password: "${JENKINS_ADMIN_PASSWORD}"
  
  authorizationStrategy:
    globalMatrix:
      permissions:
        - "Overall/Administer:admin"
        - "Overall/Read:authenticated"
  
  globalNodeProperties:
    - envVars:
        env:
          - key: "DOCKER_HOST"
            value: "unix:///var/run/docker.sock"
          - key: "ANDROID_HOME"
            value: "/opt/android-sdk"
          - key: "ANDROID_SDK_ROOT"
            value: "/opt/android-sdk"
          - key: "JAVA_HOME"
            value: "/usr/local/openjdk-21"
          - key: "NODE_VERSION"
            value: "20.12.0"
          - key: "GRADLE_HOME"
            value: "/opt/gradle"
          - key: "GRADLE_VERSION"
            value: "8.5"

credentials:
  system:
    domainCredentials:
      - credentials:
          - usernamePassword:
              scope: GLOBAL
              id: "azure-devops-git"
              username: "${AZURE_DEVOPS_USERNAME}"
              password: "${AZURE_DEVOPS_PAT}"
              description: "Azure DevOps Git credentials"
          - string:
              scope: GLOBAL
              id: "azure-devops-npm-token"
              secret: "${AZURE_DEVOPS_NPM_TOKEN}"
              description: "Azure DevOps NPM registry token"
          - string:
              scope: GLOBAL
              id: "firebase-token"
              secret: "${FIREBASE_TOKEN}"
              description: "Firebase CLI token"
          - file:
              scope: GLOBAL
              id: "env-file-qa"
              fileName: "envqa.txt"
              secretBytes: "${ENV_FILE_QA_PATH}"
              description: "Archivo de entorno para QA"
          - file:
              scope: GLOBAL
              id: "env-file-uat"
              fileName: "envuat.txt"
              secretBytes: "${ENV_FILE_UAT_PATH}"
              description: "Archivo de entorno para UAT"

          - file:
              scope: GLOBAL
              id: "release-keystore-file"
              fileName: "release.keystore"
              secretBytes: "${RELEASE_KEYSTORE_PATH}"
              description: "release.keystore (File credential con el archivo keystore)"
          - string:
              scope: GLOBAL
              id: "release-keystore-password"
              secret: "${RELEASE_KEYSTORE_PASSWORD}"
              description: "release-keystore-password"
          - string:
              scope: GLOBAL
              id: "release-key-alias"
              secret: "${RELEASE_KEY_ALIAS}"
              description: "release-key-alias"
          - string:
              scope: GLOBAL
              id: "release-key-password"
              secret: "${RELEASE_KEY_PASSWORD}"
              description: "release-key-password" 